sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: d8DfuYLtCN6t3JSa9VSFFdmanNiBZ/zmv7HFDffejpcu6xh/3rtwodI/g2DJJlmbGdciGZLtbRi19gBDlxwimBarFWfrty5OaRUamrS4w3JMPDhIgU/chnqmtgskhppf9SkO2O6BfqQRBPh8DwhwZaBiOj3pxfInoLi78Z93XQ5C/Nha6J6qwZe9UUv/348JWqVZl2h3RGn4XO9BF2lVqfLtRw7c/mW4VhVVW7oswQvemdHLBY2eKJI9Iwrzqrt94mm/R6Fq0/qSAPqcENkz7EtoPD0d2WIxtQ8g+F/OZjhwhPRAKDGlab2xz6dugFPxUPUBbGP/6OWTMGDDH31sOzuXDGNKLxeGOPMYNpe0UGg6rhgrVMC9D9szWCZjudKGIU5w8SL/rWTNs5ySfdTxLb7pzn/pKM41jjxYp2nnqlQisFA4ZoNJrwHwoUNHd1+9Xff2tVZ9yWyOF4lPgQyXREWsaF3Ni4u2vUeoWgIzWDnn3cT9b5bcL/8OoFP5FqxfUjILH6IyCI7/Qq80w4+MXxhirAp+X5hsE0mQjufq9GXI1DDEOqrbkzik9TWBzZ6O6HW7oDDiqE5wAU6krtnxyimWLK/m+l4gp7Lc7PYDzFezYJjrONFXUoJUuNlhm2+E9dFS/VmsyTM11wDDQPYftu9dZx56PjKfv2Wk7a1Audw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Les-Cenci_801
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy